server:
  port: 2121

spring:
  DataSource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    passward: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update